# Generated by Django 2.1.7 on 2019-03-31 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_auto_20190329_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
