# Generated by Django 2.1.7 on 2019-03-31 21:09

import constructor.tokens
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_auto_20190331_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='confirmation_token',
            field=models.CharField(default=functools.partial(constructor.tokens.generate_token, *(64,), **{}), max_length=64),
        ),
    ]
